package com.episen.ing3.tpmra.configuration;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-12-02T13:05:00.076Z[GMT]")
@Configuration
public class SwaggerDocumentationConfig {


    @Bean
    public OpenAPI configure() {
        return new OpenAPI()
            .info(new Info()
                .title("Documents Management")
                .description("No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)")
                .termsOfService("")
                .version("1.0.0")
                .license(new License()
                    .name("MIT")
                    .url("http://unlicense.org"))
                .contact(new Contact()
                    .email("")));
    }

}
